### ISSUE TITLE
Figure out who's planning to attend the main event

### ISSUE THREAD

**Issue by PeteSteinfeld** [HilHi-Technology/Contrast#41]
We need to figure out who's going to attend the main event.  For those folks, we need to get permission slips and emergency contact information.  Last year we captured the name, position, role, phone, contact person, contact person phone, email address, and contact person email address.

Also, if we know that we're going to have 10 or more team members attending, we need to notify Arian Kulp, the organizer of OGPC.

Also, we should make sure that Ms. Wilson has the contact information.

This issue can be resolved when we have the contact spreadsheet and have sent email to Arian Kulp.

**Comment by jmalexan** [comment]
- Jonathan
- Matthew
- Skyler
- Melissa
- Philippe
- Alex
- Tin
- Matthew
- Ethan
- JT
- Alejandro
- Dakota
- Stephen
- Grahm
- Pete
- Terry

This is greater than 10 people, so Pete will notify Arian we will need a bigger space
